# Generated by Django 5.0.8 on 2025-12-27 19:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def populate_tracking_tokens(apps, schema_editor):
    campaign_recipient = apps.get_model("campaigns", "CampaignRecipient")
    for recipient in campaign_recipient.objects.filter(tracking_token__isnull=True):
        recipient.tracking_token = uuid.uuid4()
        recipient.save(update_fields=["tracking_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrecipient",
            name="clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="tracking_token",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_tracking_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="campaignrecipient",
            name="tracking_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("open", "Open"), ("click", "Click")], max_length=16
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.campaignrecipient",
                    ),
                ),
            ],
        ),
    ]
