# Generated by Django 5.0.8 on 2025-12-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaignrecipient_clicked_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailevent",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="cta_clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="landing_view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="landing_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="open_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="open_signal_quality",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="report_channel",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="submit_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="submit_attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="time_to_click_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="time_to_report_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="browser_family",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="device_type",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="email_client_hint",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="ip_address_truncated",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="ip_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="is_webview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="language",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="message_provider_hint",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="open_signal_quality",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="os_family",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="timezone_offset_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("click", "Click"),
                    ("landing_view", "Landing view"),
                    ("cta_click", "CTA click"),
                    ("submit_attempt", "Submit attempt"),
                    ("report", "Report"),
                ],
                max_length=16,
            ),
        ),
    ]
