# Generated by Django 5.0.8 on 2025-12-27 23:43

from django.db import migrations, models


def repair_sent_records(apps, schema_editor):
    campaign_recipient = apps.get_model("campaigns", "CampaignRecipient")
    records = campaign_recipient.objects.filter(status="sent", sent_at__isnull=True)
    for record in records:
        record.sent_at = record.created_at
        record.data_repaired = True
        record.save(update_fields=["sent_at", "data_repaired"])


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_remove_emailevent_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrecipient",
            name="cta_click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="data_repaired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="fail_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(repair_sent_records, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="campaignrecipient",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("bounced", "Bounced"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
