# Generated by Django 5.0.8 on 2026-01-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaignrecipient_cta_click_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipientTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="recipient",
            name="area",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipient",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipient",
            name="last_name_maternal",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipient",
            name="last_name_paternal",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recipient",
            name="role",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="campaign",
            name="recipient_tags",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="campaigns.recipienttag"
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipients", to="campaigns.recipienttag"
            ),
        ),
    ]
